### ISSUE TITLE
Hidden Folders Content Don't Always Show

### ISSUE THREAD

**Issue by seniorm0ment** [SimpleMobileTools/Simple-Gallery#1682]
Sometimes when you "temporarily show hidden folders" they show but you click them and the photos inside don't appear. Even if you wait. Kinda annoying to be quite honest, hope to see it get fixed.

Android Pie, LGv40

**Comment by tibbi** [comment]
what app version are you using?

**Comment by Z3ROGRAV1TYx** [comment]
@tibbi 6.10.7

**Comment by tibbi** [comment]
try with the latest 6.11.3 please

**Comment by Z3ROGRAV1TYx** [comment]
That version hasn't been pushed to fdroid yet, I can't update with the apk it just fails

**Comment by tibbi** [comment]
aha, the f-droid version wont be updated for a while now due to the new editor, but guess I can keep the ticket here

**Comment by Z3ROGRAV1TYx** [comment]
@tibbi welp, ok i'll wait.
just so i can get an idea, about how long? few weeks? months?

**Comment by tibbi** [comment]
no idea, most likely months

**Comment by Z3ROGRAV1TYx** [comment]
f ok.

**Comment by tibbi** [comment]
try with the latest f-droid version 6.13.4, it should be fixed there. Reopen if not.

**Comment by grravity** [comment]
> 
> 
> try with the latest f-droid version 6.13.4, it should be fixed there. Reopen if not.

Nope, still having the issue. Can you reopen this please? (or I can make a new issue if you'd like)

**To be clear, to reproduce the issue:**
Enter Simple Mobile Gallery, go into an album, select a photo or video, choose copy/move, dialog pops up asking where to copy/move to, click the eye icon to show hidden folders/albums, change directory to one of the uncovered hidden folders/albums, blank folder. 
Try again, but entering into a different hidden folder/album, same issue. 
Can't seem to fix, sometimes it works, sometimes it doesn't. Sometimes restarting the app works, other times it doesn't. I can't figure out exactly what triggers it.

The only workaround I can figure out is to instead of clicking the eye icon, to instead choose "other folders" and have it open in File Manager view, then view hidden folders with the eye icon in the file manager view, then navigate and it seems to work properly. But this is a PITA workaround to be quite honest, especially when moving around a bunch of photos.

**SysInfo:**
**Device:** LGv40 (LM-V405TA)
**OS:** Stock Android 9
**App:** Simple Mobile Gallery (F-Droid) - 6.13.4

**Comment by thevirajshelke** [comment]
I am facing the same issue using MIUI 11 with Android 10 underneath. Whenever I click on "Temporarily show hidden" nothing happens! Even if you wait for quite some time. Afaik it used to work previously (long back I don't remember the exact version)

As of now, I am using simple gallery pro v6.14.9. Kindly fix this on a high priority.  This bug is irritating since we cannot see hidden folders and deal with them.

This feature comes handy when we want to see the WhatsApp sent items etc. which have the .nomedia file present i.e. are hidden.

**Comment by tibbi** [comment]
something has changed in 6.14.9 already. Just try adding the misbaving folders in the app settings -> manage included folders, and once they show up you can remove them from there. The app will already be aware of them and visibility toggling should work.

**Comment by grravity** [comment]
> something has changed in 6.14.9 already. Just try adding the misbaving folders in the app settings -> manage included folders, and once they show up you can remove them from there. The app will already be aware of them and visibility toggling should work.

Will take a look and test for next few days if I have issues I'll report back

**Comment by thevirajshelke** [comment]
> Just try adding the misbaving folders in the app settings -> manage included folders, and once they show up you can remove them from there
@tibbi This has worked for me! Thanks for the temporary solution. 

I hope the issue will be fixed soon :) Keep the good work! Thanks :+1:

**Comment by tibbi** [comment]
well I broke something related to it in like 6.14.8 indeed, should be working better now. There will always be some not recognized folders though, it is kind of a system issue. If the system doesnt tell me that the given folder contains files, Im not aware of it. I could add some folder by folder device rescanning, but the notion of folders will be heavily changed soon and I wont be able to access files directly, so I probably wont work on that recursive scan.

**Comment by thevirajshelke** [comment]
> well I broke something related to it in like 6.14.8 indeed, should be working better now.

Great!

> There will always be some not recognized folders though, it is kind of a system issue. If the system doesn't tell me that the given folder contains files, I'm not aware of it.

I see so seems like an OS-level issue? Is it happening only in Android 10 or previous android versions as well!

> I could add some folder by folder device rescanning, but the notion of folders will be heavily changed soon and I won't be able to access files directly, so I probably won't work on that recursive scan.

I am not sure as to what "notion of folders will be heavily changed soon" means but if you want to do a recursive scan how about you skip (exclude) some folders (OS folders which users don't deal with) by default? Just add them by default to the exclude list like the Android folder, etc. Maybe I am wrong here & you already do it. Just a thought came in my mind so shared :)

> There will always be some not recognized folders though, it is kind of a system issue.

Would be great if you write some note in the play store app description or write the solution of using 'Just try adding the misbehaving folders in the app settings -> manage included folders, and once they show up you can remove them from there' in the FAQ section :) :+1: 

Thanks btw :+1:

**Comment by tibbi** [comment]
it is already mentioned in the FAQ section, but there will always be people not reading anything, just writing emails

**Comment by grravity** [comment]
Still seem to be having this issue on F-Droid v6.15.5
Tried doing the workaround again, and still seems to bug out sometimes and work fine others.

**Comment by tibbi** [comment]
closing this as with version 6.23.0 and Android 11+ you wont be able to see hidden files anymore

**Comment by seniorm0ment** [comment]
wtf, they blocked access to see hidden files?

**Comment by tibbi** [comment]
for such apps ye. Just try out any gallery updated after November 2021 with Android 11+ to see how it behaves. Maybe some f-droid apps ignore some Google rules, but I dont want go that way.

**Comment by tibbi** [comment]
no, it is a big change, I dont want to maintain 2 so different app versions
