### ISSUE TITLE
Slow folder opening after upgrade to Android 11

### ISSUE THREAD

**Issue by szpak** [SimpleMobileTools/Simple-Gallery#1905]
After upgrade to Android 11 (Pixel 3a) I started observing degraded performance in opening folders with photos.

Every time, when I open a folder with 1,5K of photos it takes ~7 seconds. When I opened it for the first time it was even 20 seconds (but something might get cached at the Android level and even killing the app gives still 7 seconds). When the photos are loaded, scrolling or opening particular photos works smoothly.

When I first opened Simple Gallery (6.15.2 Pro) after upgrade there were presenting different numbers of files in particular folders (Camera and some other custom folders in the Pictures folder). Those values were changed over time and the order of folders displayed on the main screen was changing multiple times. It took a few (several?) minutes to stabilize (before that I wasn't able to see any photos entering the Camera folder in the app). Currently it is presented ok, however, occasionally, I still see wrong number of files in the Camera folder (e.g. 1,2K instead of 1,5K).

I don't know if it might be related to the [introduction](https://www.reddit.com/r/androiddev/comments/ga5u72/saf_is_so_slow/) of  Storage Access Framework (SAF) and what else changed internally in 11. I have no idea if anything can be tuned up at the Simple Gallery level. I create this issue as Android 11 has been released just yesterday, so there is a chance that more people will hit this problem later on. 

As a reference in Android 10 it was (almost) instantaneous, even with 4K of photos in one folder. All the files are on the internal storage (not SD card).

**Comment by tibbi** [comment]
try upgrading to 6.15.3 once it becomes available, it started rolling out yesterday

**Comment by Lekensteyn** [comment]
Not sure how much it would help without significant changes. Even `adb shell time ls -latr /sdcard/DCIM/Camera` with 3k files takes 18 seconds (Pixel 2, Android 11). During that operation, the `com.google.android.providers.media.module` process is spending a good amount of CPU time. Before an upgrade from Android 10, it was near instant.

**Comment by tibbi** [comment]
what sorting are you using there? Try some different ones and disable grouping.

**Comment by szpak** [comment]
> try upgrading to 6.15.3 once it becomes available

Thanks for a quick response with the new version. First of all, it relived with the main problem - waiting a few seconds every time I wanted to enter the main directory with the camera photos (~1,5K files after reduction). It opens immediately, thanks!

Just to complete the report, occasionally, there are some glitches. It's is especially, visible if I take a photo and enter the gallery right after that. The photo is not visible for some time - most likely due to caching. However, knowing about that I can force refresh and (after several seconds) I have it (or wait if I don't need it right now), so it's not a problem for me. Especially that I don't know if you can do anything about that as looking at the other apps I observe similar slowdown (e.g. entering Total Commander to the DCIM directory it also takes a few long seconds to see the files).

However, there is something I don't fully understand. If I remove (move to the trash bin) files (e.g. two newly taken), I step out to the main gallery window, usually, I see smaller number of photos in the Camera folder. - different numbers (~400, ~700, 16). When I enter the Camera folder then - for some time - I just see that subset of photos.

I use "Last modified" descending sorting and grouping by Date taken (monthly) also descending. I will play with different settings.

Btw, I don't know if it complicated anything, but the new photos are named `PXL*` instead of `IMG*` (or `MIMG*`) which is after `I` in the alphabetical order.

**Comment by szpak** [comment]
Some more observations. When I enabled portraits (in filter media) - it seems to be disabled when I originally reported that problem - the problems with slow directory opening occurred again.

Disabling grouping (independently to portraits) also slightly improve load time.

**Comment by szpak** [comment]
@Lekensteyn Have you [reported](https://source.android.com/setup/contribute/report-bugs) that problem upstream? `adb shell time ...` is much easier to reproduce than referring to the 3rd party application.

**Comment by tibbi** [comment]
if I send you a test app version can you try it out? You will have to reinstall the app. Try also selecting "Speed" as the file loading priority in the app settings and disable Portrait file showing for now. It is a ridiculous filetype that is difficult to detect, so I disabled it by default. Let me know at hello@simplemobiletools.com if you want the test version, it is easier to send files via email.

**Comment by tibbi** [comment]
should be fixed in 6.15.4

**Comment by snintendog** [comment]
As a side note due to SAF the issues still exist and will keep getting mentioned as the roll out of the os infects more phones but excluding the SD card entirely speeds up performance really efF SAF.
