### ISSUE TITLE
When drawing, the line appears offset

### ISSUE THREAD

**Issue by tm-107** [SimpleMobileTools/Simple-Gallery#2694]
When I edit an image in the current version, drawn lines appear offset on the screen.

Device: Xiaomi Mi A2 lite

With version 6.25.4 the error is not present.

**Comment by tibbi** [comment]
it has been fixed already, just needs an app update

**Comment by tm-107** [comment]
Sorry, in F-Droid 6.25.5 is the latest version. And the error is still there.
So I will wait for the next update in F-Droid.

**Comment by tibbi** [comment]
ye, I mean that we have to release an update, it isnt available anywhere yet
