### ISSUE TITLE
Delete option sometimes doesn't work

### ISSUE THREAD

**Issue by Akhilesh-T** [SimpleMobileTools/Simple-Gallery#2783]
Hi,

I've been facing this issue for quite sometime now. Sometimes, when I delete a file, it doesn't work. This doesn't happen with the in-built gallery app.

I'm using Samsung M51 with Android 12
Simple Gallery version: 6.26.3

Here's a recording to show you the issue. The deleted file reappears after I refresh.

https://user-images.githubusercontent.com/80357467/220823944-5128c19d-f398-421d-9449-0f68661d7516.mp4

**Comment by Aga-C** [comment]
Do you mean Whatsapp folder, or does it happen in other folders too?

**Comment by Akhilesh-T** [comment]
Other folders as well, including recycle bin

**Comment by kyoyacchi** [comment]
Same here. I oftenly have this problem while trying to delete videos

**Comment by aashionic** [comment]
I am also facing this problem in Android 12L

**Comment by tibbi** [comment]
can you guys check the test version at https://github.com/SimpleMobileTools/Simple-Gallery/issues/2759#issuecomment-1465270708 ?

**Comment by Akhilesh-T** [comment]
I haven't faced this issue since the recent play store update. But I'll need some more days to be absolutely sure, because the issue doesn't happen all the times.

**Comment by aashionic** [comment]
its fixed with the latest update i guess, working fine for me !

**Comment by Akhilesh-T** [comment]
Issue still not resolved

https://github.com/SimpleMobileTools/Simple-Gallery/assets/80357467/fe33677c-7aa3-4fdb-affd-7d43960c6930

**Comment by tibbi** [comment]
those are apparently some corrupt mediastore entries, not existing files. Does some file manager show them at all?

**Comment by Akhilesh-T** [comment]
I am able to play all 4 of these media files even after I delete any one of them.
