### ISSUE TITLE
image is shown with weird artifacts

### ISSUE THREAD

**Issue by tessus** [SimpleMobileTools/Simple-Gallery#343]
This applications is awesome. 

Unfortunately I've noticed a slight issue. The following image:

![spheres sunset 1080x1920](https://user-images.githubusercontent.com/223439/29902271-0f740bb6-8dcb-11e7-9142-6e26554f4876.jpg)

is shown in Gallery like this:

(notice the artifacts in the grey sky?)

![screenshot_20170830-212702](https://user-images.githubusercontent.com/223439/29902201-99b14e98-8dca-11e7-98ae-504b5fb8928e.png)

**Comment by tessus** [comment]
I just wanted to add a few things. Maybe it helps to track down the issue:

- this happens with other images as well, but it can't be seen that easily as with the example above
- when you go back and forth between 2 images (swipe left or right), the image is shown correctly for about half a second, then these artifacts show up.

**Comment by tibbi** [comment]
ye I know whats the issue and how to fix it, a new version should be available in a couple days. Just need to tweak a few more things.

**Comment by tessus** [comment]
@tibbi unfortunately this issue has resurfaced again.

**Comment by tessus** [comment]
shall I open a new bug and reference this issue? I can't reopen this one.

**Comment by tibbi** [comment]
I can reopen it. Im aware that its back, as many devices couldnt handle the better quality, or the zoom wasnt working well. Improving it is on the roadmap.

**Comment by tessus** [comment]
Thanks for reopening.

Maybe you could add an option in Settings until a real fix is available.

**Comment by ChristianCiach** [comment]
As I use the gallery a lot for manga and anime pictures, this issue bugs me with almost every picture. As was glad that is was finally fixed, but now it is back :(

I agree that there should be an option if it is not possible to fix it for every device.

**Comment by tessus** [comment]
I had to switch to a different app. I love this app, but I can't use it when pictures are not displayed correctly. A simple grey gradiant showing as block artifacts is a joke. I understand that the author mentioned that other people had issues with the fix. Well, I have an issue without the fix.
(I also suggested to make it an optional setting.)
Anyway, I had to find another app that displays images correctly.

Too bad, because I really loved this app.

**Comment by tibbi** [comment]
ye I will be adding a toggle for replacing deep zoomable images with better quality ones in the next version released in 1-2 days, that should fix it. Ideally I want to have both in the future, it just isnt that simple. Thanks

**Comment by tessus** [comment]
I can confirm that the switch (when turned on) solved the problem for me. Thank you.

(deleting other app again...)

**Comment by scalpremier** [comment]
Hello

I think the problem isn't realy solved.

The better quality option seems to work only when the image is at the screen size, but when you try to zoom in, it's blurry.

On your test image it's not very visible because the image is small. But with a bigger image with, for exemple, an blue sky gradient background and sharp first plan it's visible. 

I've try Camera Roll another opensource gallery available on f-droid, they have the same issue, but they have a 8 bit color mode who fix it even when you zoom in the image.

Maybe you should have a look.

I've opened a issue to request this feature. 

Thanks a lot.

**Comment by tibbi** [comment]
I think I found the ideal solution. Starting with version 4.5.0 the toggle will be removed, I will load a zoomable image that will also have good quality. Let me know at hello@simplemobiletools.com if you want to test the version.

**Comment by ChristianCiach** [comment]
It's awesome! I cannot find an issue. 

Maybe it has been already fixed earlier, but "double tap and slide" works flawless now. Before, it was very easy to accelerate the zoom in a way that it completely broke, even so much that the image got flipped in the process. This is fixed now.

**Comment by ChristianCiach** [comment]
When zoomed in, scrolling is sluggish with some images, but perfectly smooth with others (of the same size, taken with the same camera). It doesn't bother me, but I wonder why this is.

**Comment by tibbi** [comment]
Im not sure, it still isnt fully done, I was just testing a prototype. Ill see what more can be improved in the future. Thanks

**Comment by tessus** [comment]
I've tested the new version. The setting `Replace deep zoomable images with better quality ones` is still available, therefore I deactivated it.
I don't see a difference between the images when the setting is off or on. The images look ok to me. I don't see any artifacts anymore.

**Comment by tibbi** [comment]
ye the toggle is still visible in this test version, but it is ignored. Im always loading a deep zoomable image with good quality. Seems to be working well so far :) Thanks

**Comment by tibbi** [comment]
Ill close this, reopen if there are still some related issues with version 4.5+

**Comment by ChristianCiach** [comment]
Just because I am curious: The main thing you changed is to use the Picasso library now?

**Comment by tibbi** [comment]
Im still using SubsamplingScaleImageView, but instead of the default region decoder Im using Picasso for that. You can specify a part of the image that should be loaded there, you dont have to load the whole image at once. For the initial fullscreen images I also switched to Picasso, for the thumbnails Glide :D We will see how will it work.

**Comment by utack** [comment]
Unfortunately I found it again  
It actually takes a second then it "jumps" from an ok (thumbnail?) version to a banded version


File:
https://i.redd.it/d1aehdnbq0h21.jpg

![screenshot_2019-02-17-02-39-11-476_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/8551234/52907325-ef533380-325f-11e9-9f4a-6f5e9e795d7e.png)
![screenshot_2019-02-17-02-39-16-932_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/8551234/52907327-f4b07e00-325f-11e9-9758-bb718d17432d.png)

**Comment by tibbi** [comment]
try enabling the "Show images in the highest possible quality" at the app settings, at Deep zoomable images section.

**Comment by utack** [comment]
Sorry, forgot to mention  
I did, and it looked the same

**Comment by tibbi** [comment]
should be better with the "Show images in the highest quality" option in 6.5.3. Zooming might be lagging a bit, but for now I dont know how to have good quality and performance too.

**Comment by KnIfER** [comment]
@tibbi the lag is simply caused by `setMaxTileSize(if (showHighestQuality) Integer.MAX_VALUE else 4096)`  (that is too extreme)

**Comment by tibbi** [comment]
well if I reduce it, the quality will suffer. It should be set somehow dynamically, but I couldnt figure it out yet.
