### ISSUE TITLE
Silent crash when deleting photos on an external SD card

### ISSUE THREAD

**Issue by XyLoNaMiyX** [SimpleMobileTools/Simple-Gallery#50]
When I try to delete some photos stored in my external SD card (more specifically gifs), the application silently crashes and self-closes. The app never asked me for SD card access (I'm using Android 5.0 Lollipop), and thus the photos remain untouched.

**Comment by XyLoNaMiyX** [comment]
See the crash log gist [here](https://gist.github.com/XyLoNaMiyX/f4a4f1c4c3efbf20275c741f1dd7bcd9#file-crash-log-L35-L42). The path is something like `/storage/sdcard1/photos/somefile.gif` so I don't understand how that is an "Invalid URI".

**Comment by tibbi** [comment]
Hey, thanks for the report and the gist! It should be fixed with the next version 1.30. The invalid URI is not the one of your file, its related to that ridiculously stupid Android 5+ new SD card write permission.

**Comment by XyLoNaMiyX** [comment]
Haha okay thanks for the fix! I didn't know where else I should look to help out.

And I have to agree that the SD card write permission is quite annoying ;)

**Comment by XyLoNaMiyX** [comment]
Not so fast @tibbi, for some reason it still doesn't ask me for SD card permission and fails [in the same place](https://gist.github.com/XyLoNaMiyX/ff9d428088a32795ff7ae0f52a04b356#file-crash-log-L32-L39) (trying with your [latest commit](https://github.com/SimpleMobileTools/Simple-Gallery/commit/8108a109dcdaafa22499a0985d1be5daf9027ef3)).

I even cleared app data, uninstalled, and restarted phone (Android does weird stuff with the write permissions after rebooting; I've also had some issues with this and OpenCamera, where I need to re-ask manually after rebooting).

Also tried renaming the folder. You guessed it, same result, it also crashes, and never asks for permission. But not asking for permission should perhaps be a different issue.

**Comment by tibbi** [comment]
maybe the SD card path is not detected properly. Can you please check at the beginning of deleteItem(File file), which of the conditions is not true? One of these:
!file.canWrite()
Config.newInstance(activity).treeUri.isEmpty()

**Comment by XyLoNaMiyX** [comment]
Yes, I was exactly checking those three from `isShowingWritePermissions`, but I don't know how the heck I log something on the console in Kotlin! Hold on.

**Comment by XyLoNaMiyX** [comment]
`file.canWrite()` returns `true`, so it does **not** enter the condition. Maybe you should use `||` instead `&&` (at least for the `canWrite` and `treeUri.isEmpty()` part, which is the one missing)?

**Comment by XyLoNaMiyX** [comment]
I think the reason for it to show so many pops up is that, after I click "OK, I'll select the SD card" the dialog closes, and thus it opens another one (because it's still trying to delete more files I assume).

**Comment by tibbi** [comment]
okay cool, thanks a lot. I dont feel like messing around with it even more, should be good enough.

**Comment by XyLoNaMiyX** [comment]
Everything working @tibbi. When renaming it only shows the pop up once if you click outside (to cancel), but when deleting the whole folder, a second dialog pops up (with one element in the folder). Still, the problem is fixed and this only happens once!

**Comment by tibbi** [comment]
ok thanks :) Thats good enough, I dont want to spend more time with it.
