### ISSUE TITLE
"App icon color" doesn't work

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#772]
It just doesn't work. Video for reference:
https://my.mixtape.moe/pigzmd.mp4

**Comment by tibbi** [comment]
what Android OS version and what launcher do you have? Is it a rooted device?

**Comment by floppyD** [comment]
Oh yes, I forgot.
8.1.0 - AOSP Extended
Launcher3 (https://github.com/amirzaidi/launcher3)
Yes, with magisk.

Maybe it's the launcher not handling things properly? If that so, could you create a issue on its github? I don't even know how this customizable icon thing is called, it's the first time I saw an app using it.

**Comment by tibbi** [comment]
ye it is definitely an issue on their side, Ill check it out someday

**Comment by sabi0** [comment]
It also does not work with Nova Launcher for me.
Even after rebooting the phone I still see the default icon color.

**Comment by tibbi** [comment]
can you maybe check it at the calculator https://play.google.com/store/apps/details?id=com.simplemobiletools.calculator ? It is done a bit differently there as I forgot to update a line.

**Comment by sabi0** [comment]
It does not work in calculator v4.0.0 either.
After I changed the launcher icon color setting the desktop icon disappeared after about 30 seconds.
But it still shows the default color in the app drawer. And when I dragged the app to the desktop it was still displayed in default color.

**Comment by sabi0** [comment]
I figured out where is the problem.
I don't quite like some "modern" icons in Google apps on Android 8+ (e.g. Chrome). So I had "Prefer legacy icons" option enabled in Nova Launcher.
As soon as I disabled it the Simple Galery icon became "adaptive". And also changed the color as configured.

P.S. The TickTick app icon is "adaptive" even with the "Prefer legacy icons" enabled. Does it mean they don't have "legacy" icon in the app? Or is there a way to make legacy icons adaptive too?

**Comment by tibbi** [comment]
I dont know, launcher icons are one of the areas which can vary depending on the launcher. It should work just fine with legacy icons too. I tested Nova Launcher too and it worked fine, but I have every setting on the default value, I wasnt changing anything. I will take a look at it someday. Thanks

**Comment by sabi0** [comment]
The setting I was talking about is at Look & feel > Adaptive icon style, at the very bottom.

**Comment by sabi0** [comment]
And here are two more screenshots showing how TickTick app legacy icon reacts to changing the shape in Nova Launcher while Simple Galery's icon is always a circle.
Both these screenshots were taken with "Prefer legacy icons" = on.

![image](https://user-images.githubusercontent.com/11509875/40238891-c9010672-5ab4-11e8-8283-da7b86184334.png)  ![image](https://user-images.githubusercontent.com/11509875/40238913-d94a54d4-5ab4-11e8-9a15-250137128092.png)

**Comment by tibbi** [comment]
so you have Android 8+?

**Comment by sabi0** [comment]
Yes. Sorry, I thought that was clear from adaptive icons reference which were introduced in Android 8.0
I am actually on Android 8.1.0. A "vanilla" one from Google. No root.

**Comment by williamd1k0** [comment]
Hi, I'm having the same issue on Lawnchair (based on Launcher3).
I fixed it disabling the "Use Pixel icons" option.
I don't know what is happening tho.

![image](https://user-images.githubusercontent.com/10428035/40465592-cf2929ac-5ef7-11e8-9a8c-b15e7b00e907.png)

**Comment by tibbi** [comment]
I tried Launcher3 itself, seems to work fine with everything set to default. Ill see how can I improve it in the future, if theres anything I can do on my side. I know what are those launchers doing wrong as I was recently working with getting proper launcher color at my app-launcher https://github.com/SimpleMobileTools/Simple-App-Launcher too.

**Comment by tibbi** [comment]
should be fixed already, especially from version 4.3.4. Reopen if not.

**Comment by sabi0** [comment]
It still does not work in Nova Launcher with 4.3.5 I received yesterday.
When changing the icon color the shortcut stops working ("App not installed") or just disappears from the home screen. After adding it back by dragging the app icon from the drawer the shortcut still does not work. Reboot fixes the "App not installed" problem.
At all times both the home screen shortcut icon as well as app drawer icon have default orange color.

**Comment by xmiseggs** [comment]
Still doesn't work on my case with the CPL launcher. Isn't it better to remove this option, I see that only gives problems with almost all launchers.

**Comment by ouzowtf** [comment]
But it is a problem of the launcher, not of Simple Gallery. Since one or two months it works in Nova Launcher again.

**Comment by tibbi** [comment]
duplicate of https://github.com/SimpleMobileTools/General-Discussion/issues/83
